import '../globals.css'



export const metadata = {
  title: 'beerloyuz.com - Giriş yap/Kayıt ol',
  description: 'Generated by beerloyuz',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
    <div className='flex items-center justify-center h-screen'>
      {children}
    </div>
  )
}
